FROM ollama/ollama:latest
# docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
# docker exec -it ollama ollama run codellama
# docker cp ollama:/root/.ollama/   ./
COPY ./.ollama/ /root/.ollama/